/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TagAdminRouteImport } from './routes/tag-admin'
import { Route as SmartTagsRouteImport } from './routes/smart-tags'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as JewelleryRouteImport } from './routes/jewellery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CustomGiftsRouteImport } from './routes/custom-gifts'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CancellationPolicyRouteImport } from './routes/cancellation-policy'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTagIdRouteImport } from './routes/tag.$tagId'
import { Route as MyTagSetupRouteImport } from './routes/my-tag.setup'
import { Route as MyTagLoginRouteImport } from './routes/my-tag.login'
import { Route as MyTagEditRouteImport } from './routes/my-tag.edit'
import { Route as MyTagDashboardRouteImport } from './routes/my-tag.dashboard'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TagAdminRoute = TagAdminRouteImport.update({
  id: '/tag-admin',
  path: '/tag-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartTagsRoute = SmartTagsRouteImport.update({
  id: '/smart-tags',
  path: '/smart-tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const JewelleryRoute = JewelleryRouteImport.update({
  id: '/jewellery',
  path: '/jewellery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomGiftsRoute = CustomGiftsRouteImport.update({
  id: '/custom-gifts',
  path: '/custom-gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationPolicyRoute = CancellationPolicyRouteImport.update({
  id: '/cancellation-policy',
  path: '/cancellation-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagIdRoute = TagTagIdRouteImport.update({
  id: '/tag/$tagId',
  path: '/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTagSetupRoute = MyTagSetupRouteImport.update({
  id: '/my-tag/setup',
  path: '/my-tag/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTagLoginRoute = MyTagLoginRouteImport.update({
  id: '/my-tag/login',
  path: '/my-tag/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTagEditRoute = MyTagEditRouteImport.update({
  id: '/my-tag/edit',
  path: '/my-tag/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTagDashboardRoute = MyTagDashboardRouteImport.update({
  id: '/my-tag/dashboard',
  path: '/my-tag/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/custom-gifts': typeof CustomGiftsRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jewellery': typeof JewelleryRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/smart-tags': typeof SmartTagsRoute
  '/tag-admin': typeof TagAdminRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/my-tag/dashboard': typeof MyTagDashboardRoute
  '/my-tag/edit': typeof MyTagEditRoute
  '/my-tag/login': typeof MyTagLoginRoute
  '/my-tag/setup': typeof MyTagSetupRoute
  '/tag/$tagId': typeof TagTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/custom-gifts': typeof CustomGiftsRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jewellery': typeof JewelleryRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/smart-tags': typeof SmartTagsRoute
  '/tag-admin': typeof TagAdminRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/my-tag/dashboard': typeof MyTagDashboardRoute
  '/my-tag/edit': typeof MyTagEditRoute
  '/my-tag/login': typeof MyTagLoginRoute
  '/my-tag/setup': typeof MyTagSetupRoute
  '/tag/$tagId': typeof TagTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRoute
  '/cancellation-policy': typeof CancellationPolicyRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate': typeof CorporateRoute
  '/custom-gifts': typeof CustomGiftsRoute
  '/faqs': typeof FaqsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jewellery': typeof JewelleryRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/smart-tags': typeof SmartTagsRoute
  '/tag-admin': typeof TagAdminRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/my-tag/dashboard': typeof MyTagDashboardRoute
  '/my-tag/edit': typeof MyTagEditRoute
  '/my-tag/login': typeof MyTagLoginRoute
  '/my-tag/setup': typeof MyTagSetupRoute
  '/tag/$tagId': typeof TagTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/custom-gifts'
    | '/faqs'
    | '/forgot-password'
    | '/jewellery'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/smart-tags'
    | '/tag-admin'
    | '/terms'
    | '/wishlist'
    | '/my-tag/dashboard'
    | '/my-tag/edit'
    | '/my-tag/login'
    | '/my-tag/setup'
    | '/tag/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/custom-gifts'
    | '/faqs'
    | '/forgot-password'
    | '/jewellery'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/smart-tags'
    | '/tag-admin'
    | '/terms'
    | '/wishlist'
    | '/my-tag/dashboard'
    | '/my-tag/edit'
    | '/my-tag/login'
    | '/my-tag/setup'
    | '/tag/$tagId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/blog'
    | '/cancellation-policy'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate'
    | '/custom-gifts'
    | '/faqs'
    | '/forgot-password'
    | '/jewellery'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-policy'
    | '/shipping-policy'
    | '/shop'
    | '/smart-tags'
    | '/tag-admin'
    | '/terms'
    | '/wishlist'
    | '/my-tag/dashboard'
    | '/my-tag/edit'
    | '/my-tag/login'
    | '/my-tag/setup'
    | '/tag/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRoute
  CancellationPolicyRoute: typeof CancellationPolicyRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CorporateRoute: typeof CorporateRoute
  CustomGiftsRoute: typeof CustomGiftsRoute
  FaqsRoute: typeof FaqsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JewelleryRoute: typeof JewelleryRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SmartTagsRoute: typeof SmartTagsRoute
  TagAdminRoute: typeof TagAdminRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  MyTagDashboardRoute: typeof MyTagDashboardRoute
  MyTagEditRoute: typeof MyTagEditRoute
  MyTagLoginRoute: typeof MyTagLoginRoute
  MyTagSetupRoute: typeof MyTagSetupRoute
  TagTagIdRoute: typeof TagTagIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag-admin': {
      id: '/tag-admin'
      path: '/tag-admin'
      fullPath: '/tag-admin'
      preLoaderRoute: typeof TagAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-tags': {
      id: '/smart-tags'
      path: '/smart-tags'
      fullPath: '/smart-tags'
      preLoaderRoute: typeof SmartTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellery': {
      id: '/jewellery'
      path: '/jewellery'
      fullPath: '/jewellery'
      preLoaderRoute: typeof JewelleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-gifts': {
      id: '/custom-gifts'
      path: '/custom-gifts'
      fullPath: '/custom-gifts'
      preLoaderRoute: typeof CustomGiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation-policy': {
      id: '/cancellation-policy'
      path: '/cancellation-policy'
      fullPath: '/cancellation-policy'
      preLoaderRoute: typeof CancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tagId': {
      id: '/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/tag/$tagId'
      preLoaderRoute: typeof TagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tag/setup': {
      id: '/my-tag/setup'
      path: '/my-tag/setup'
      fullPath: '/my-tag/setup'
      preLoaderRoute: typeof MyTagSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tag/login': {
      id: '/my-tag/login'
      path: '/my-tag/login'
      fullPath: '/my-tag/login'
      preLoaderRoute: typeof MyTagLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tag/edit': {
      id: '/my-tag/edit'
      path: '/my-tag/edit'
      fullPath: '/my-tag/edit'
      preLoaderRoute: typeof MyTagEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tag/dashboard': {
      id: '/my-tag/dashboard'
      path: '/my-tag/dashboard'
      fullPath: '/my-tag/dashboard'
      preLoaderRoute: typeof MyTagDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRoute,
  CancellationPolicyRoute: CancellationPolicyRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CorporateRoute: CorporateRoute,
  CustomGiftsRoute: CustomGiftsRoute,
  FaqsRoute: FaqsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JewelleryRoute: JewelleryRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SmartTagsRoute: SmartTagsRoute,
  TagAdminRoute: TagAdminRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  MyTagDashboardRoute: MyTagDashboardRoute,
  MyTagEditRoute: MyTagEditRoute,
  MyTagLoginRoute: MyTagLoginRoute,
  MyTagSetupRoute: MyTagSetupRoute,
  TagTagIdRoute: TagTagIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
